export const API_ROUTES = {
    AUTH: {
        LOGIN: "/auth/login",
        REGISTER: "/auth/register",
        GOOGLE: "/auth/google",
    },
    USERS: {
        GET: "/users",
        EDIT: (id: number) => `/users/edit/${id}`,
        CREATE: "/users/create",
        DELETE: (id: number) => `/users/delete/${id}`,
        IMPORT_FILE: "/users/import-by-file",
        GET_BY_ID: (id: number) => `/users/${id}`,
        RESET_PASSWORD: (id: number) => `/users/reset-password/${id}`,
    },
    FILE: {
        SAVE: "/files",
        SAVE_BY_URL: "/files/url",
        DELETE: (id: string) => `/files/${id}`,
        GET: (id: string) => `/files/${id}`,
        GET_ALL: "/files",
    },
    ENTERPRISE: {
        CREATE: "/v1/enterprises",
        GET_ALL: "/v1/enterprises",
        GET_MY: "/v1/enterprises/my",
        GET_BY_ID: (id: string) => `/v1/enterprises/${id}`,
        GET_BY_SLUG: (slug: string) => `/v1/enterprises/slug/${slug}`,
        UPDATE: (id: string) => `/v1/enterprises/${id}`,
        DELETE: (id: string) => `/v1/enterprises/${id}`,
        TRANSFER_OWNERSHIP: (id: string) => `/v1/enterprises/${id}/transfer-ownership`,
        UPDATE_GOOGLE_TOKENS: (id: string) => `/v1/enterprises/${id}/google-tokens`,
    },
    ENTERPRISE_MEMBER: {
        GET_ALL: "/v1/enterprise-members",
        GET_BY_ID: (id: string) => `/v1/enterprise-members/${id}`,
        ADD: (enterpriseId: string) => `/v1/enterprise-members/${enterpriseId}`,
        UPDATE: (id: string) => `/v1/enterprise-members/${id}`,
        REMOVE: (id: string) => `/v1/enterprise-members/${id}`,
    },
    ENTERPRISE_INVITATION: {
        CREATE: (enterpriseId: string) => `/v1/enterprise-invitations/${enterpriseId}`,
        GET_ALL: "/v1/enterprise-invitations",
        GET_MY: "/v1/enterprise-invitations/my",
        GET_BY_TOKEN: (token: string) => `/v1/enterprise-invitations/token/${token}`,
        ACCEPT: (token: string) => `/v1/enterprise-invitations/token/${token}/accept`,
        DECLINE: (token: string) => `/v1/enterprise-invitations/token/${token}/decline`,
        CANCEL: (token: string) => `/v1/enterprise-invitations/token/${token}`,
    },
    CALENDAR: {
        CREATE: (enterpriseId: string) => `/v1/calendars/${enterpriseId}`,
        GET_ALL: "/v1/calendars",
        GET_MY: "/v1/calendars/my",
        GET_BY_ID: (id: string) => `/v1/calendars/${id}`,
        UPDATE: (id: string) => `/v1/calendars/${id}`,
        DELETE: (id: string) => `/v1/calendars/${id}`,
        SYNC: (enterpriseId: string) => `/v1/calendars/${enterpriseId}/sync`,
    },
    CALENDAR_EVENT: {
        CREATE: (calendarId: string) => `/v1/calendar-events/${calendarId}`,
        GET_ALL: "/v1/calendar-events",
        GET_MY_EVENTS: "/v1/calendar-events/my",
        GET_BY_ID: (id: string) => `/v1/calendar-events/${id}`,
        UPDATE: (id: string) => `/v1/calendar-events/${id}`,
        DELETE: (id: string) => `/v1/calendar-events/${id}`,
        SYNC: (calendarId: string) => `/v1/calendar-events/${calendarId}/sync`,
    },
    CALENDAR_SHARE: {
        CREATE: (calendarId: string) => `/v1/calendar-shares/${calendarId}`,
        GET_ALL: "/v1/calendar-shares",
        GET_MEMBER_SHARES: "/v1/calendar-shares/member",
        GET_BY_ID: (id: string) => `/v1/calendar-shares/${id}`,
        UPDATE: (id: string) => `/v1/calendar-shares/${id}`,
        DELETE: (id: string) => `/v1/calendar-shares/${id}`,
    },
    EMPLOYEE_GOOGLE_EMAIL: {
        ADD: (memberId: string) => `/v1/employee-google-emails/${memberId}`,
        GET_ALL: "/v1/employee-google-emails",
        GET_BY_ID: (id: string) => `/v1/employee-google-emails/${id}`,
        AUTHORIZE: (id: string) => `/v1/employee-google-emails/${id}/authorize`,
        UPDATE: (id: string) => `/v1/employee-google-emails/${id}`,
        DELETE: (id: string) => `/v1/employee-google-emails/${id}`,
    },
};
