/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SupportRouteImport } from './pages/support'
import { Route as ReportsRouteImport } from './pages/reports'
import { Route as RegisterRouteImport } from './pages/register'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as NewsRouteImport } from './pages/news'
import { Route as LoginRouteImport } from './pages/login'
import { Route as EventsRouteImport } from './pages/events'
import { Route as DonationsRouteImport } from './pages/donations'
import { Route as DirectoryRouteImport } from './pages/directory'
import { Route as DashboardsRouteImport } from './pages/dashboards'
import { Route as CareersRouteImport } from './pages/careers'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AdmDashboardRouteImport } from './pages/adm/dashboard'
import { Route as TestePortalRouteImport } from './pages/_teste/portal'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmDashboardRoute = AdmDashboardRouteImport.update({
  id: '/adm/dashboard',
  path: '/adm/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TestePortalRoute = TestePortalRouteImport.update({
  id: '/_teste/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/dashboards': typeof DashboardsRoute
  '/directory': typeof DirectoryRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/portal': typeof TestePortalRoute
  '/adm/dashboard': typeof AdmDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/dashboards': typeof DashboardsRoute
  '/directory': typeof DirectoryRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/portal': typeof TestePortalRoute
  '/adm/dashboard': typeof AdmDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/dashboards': typeof DashboardsRoute
  '/directory': typeof DirectoryRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/_teste/portal': typeof TestePortalRoute
  '/adm/dashboard': typeof AdmDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/dashboards'
    | '/directory'
    | '/donations'
    | '/events'
    | '/login'
    | '/news'
    | '/profile'
    | '/register'
    | '/reports'
    | '/support'
    | '/portal'
    | '/adm/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/dashboards'
    | '/directory'
    | '/donations'
    | '/events'
    | '/login'
    | '/news'
    | '/profile'
    | '/register'
    | '/reports'
    | '/support'
    | '/portal'
    | '/adm/dashboard'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/dashboards'
    | '/directory'
    | '/donations'
    | '/events'
    | '/login'
    | '/news'
    | '/profile'
    | '/register'
    | '/reports'
    | '/support'
    | '/_teste/portal'
    | '/adm/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  DashboardsRoute: typeof DashboardsRoute
  DirectoryRoute: typeof DirectoryRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SupportRoute: typeof SupportRoute
  TestePortalRoute: typeof TestePortalRoute
  AdmDashboardRoute: typeof AdmDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm/dashboard': {
      id: '/adm/dashboard'
      path: '/adm/dashboard'
      fullPath: '/adm/dashboard'
      preLoaderRoute: typeof AdmDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teste/portal': {
      id: '/_teste/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof TestePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  DashboardsRoute: DashboardsRoute,
  DirectoryRoute: DirectoryRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SupportRoute: SupportRoute,
  TestePortalRoute: TestePortalRoute,
  AdmDashboardRoute: AdmDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
